### ISSUE TITLE
VPC error "You may not specify a referenced group id for an existing IPv4 CIDR rule?

### ISSUE THREAD

**Issue by datatalking** [mukulmantosh/SampleDemo#1]
This was such a great tutorial, thank you for putting it together.

This error is comming up at 02:41 into the video, what setting did I miss or check incorrectly?
**What you said to click**
![Screen Shot 2022-03-24 at 9 37 17 PM](https://user-images.githubusercontent.com/11813209/160055333-6ab5b008-48fb-4d07-ae21-dbd7b60b2e80.png)

**What happens when I click it**
![Screen Shot 2022-03-24 at 9 36 50 PM](https://user-images.githubusercontent.com/11813209/160055317-ec3e6b5a-72a1-4a6f-8b30-b5e166291e19.png)

**Comment by mukulmantosh** [comment]
Oops ! This shouldn't be happening.

- Try deleting the rule and re-create once again. 
- Cross-check that the security group for Ubuntu Desktop and Postgres comes under the custom VPC (DjangoVPC).

**Comment by mukulmantosh** [comment]
Closing it for now, as didn't receive any response.
